### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by ssetty** [kraten/vehicle-speed-check#2]
Kindly explain estimate_speed function. How are values 8.8, 3.6 derived?
Thanks

**Comment by kraten** [comment]
Great question! Our bad, we have not written any comments to explain the code. We have not anticipated that so many people will star or fork this repo(these numbers may look less but still they are huge for us). Thank you!

Now, to what you asked. We have estimated these values manually for the current road to calculate pixels per metre(ppm). Therefore, the value will vary from road to road and have to be adjusted to be used on any other video.

If I talk about the part how we estimated ppm, we need to know the actual width in **metres** of the road(you can use google to find the approximate width of the road in your country). Also, we have taken the video frame and calculated the width of the road in **pixels** digitally. Now, we have the width of the road in metres from the real world and in pixels from our virtual world(video frame). To map the distances between these two worlds, we have calculated pixels per metre by dividing distance of road in pixels to metres.

**d_pixels** gives the pixel distance travelled by the vehicle in one frame of our video processing. To estimate speed in any standard unit, first we need to convert **d_pixels** to **d_metres**.

Now, it is the time to deliver the final blow (speed = d_meters * fps * 3.6). **d_meters** is the distance travelled in one frame. We have already calculated the average fps during video processing. So, to get the speed in **m/s**, just (d_metres * fps) will do. We have multiplied that estimated speed with **3.6** to convert it into **km/hr**.  I hope it's clear now :)

**Comment by ZIKO94ZIKO** [comment]
I think there is another way to calculate the actual distance in real time, it depends on the camera nail and fov and the height of the camera, so when you reassemble all these parameters you can detect the speed without knowing the real distance
