### ISSUE TITLE
#original speed

### ISSUE THREAD

**Issue by Sreejapalanivel** [kraten/vehicle-speed-check#4]
Can you provide a original speed of this video for comparison study with predicted speed?
I need to show false positive and false negative for my project for vehicle speed prediction.

**Comment by kraten** [comment]
Sorry! I do not have the video with original speed markings on it. That's the reason, I have not mentioned about its accuracy. However, you could try with another video and calculate its accuracy. But for that, you need to make to some careful adjustments. Good luck :)
